/**********************************************
 LoE World localization deDE  Rev 4  
 24.1.2013
**********************************************/

-- 23.11.2012
set @questid = 7062;
UPDATE quests_localized SET CompletionText	= 'Das Winterhauchfest, sagt Ihr? Ach, in vergangenen Zeiten hatte es eine wesentliche Bedeutung für uns Zwerge. Heutzutage scheint es, als ob Andere daraus die Geschichte von Altvater Winter gemacht haben, welche helfen soll, mehr Süßigkeiten und Geschenke zu verkaufen.$B$BEs ist keine Überraschung, dass Goli verbittert über diese Art von Veränderung ist. Er und andere Zwerge, die wie er sind, klammern sich dabei an die Vergangenheit wie ein Kriegsbanner. Während ich denke, dass eine kleine Feier immer gut ist, ist es auch wichtig, an die Ursprünge des Festes zu erinnern.' WHERE entry=@questid AND language_code='deDE';

set @questid = 8788;
UPDATE quests_localized SET CompletionText	= 'Dieses Geschenk sieht aus, als wäre es schon ein paar Mal geschüttelt worden. Auf dem Kärtchen steht:$b$bFür $N, einen ganz besonderen Helden.' WHERE entry=@questid AND language_code='deDE';

set @questid = 8768;
UPDATE quests_localized SET CompletionText	= 'Auf diesem festlich verpackten Geschenk steht Euer Name!$b$bWarte, hat sich das etwa gerade bewegt? ' WHERE entry=@questid AND language_code='deDE';

set @questid = 8744;
UPDATE quests_localized SET CompletionText	= 'Auf dem Kärtchen an diesem Geschenk steht:$b$bFür $N,$B$BMöge Euer Winterfest fröhlich und heiter verlaufen! ' WHERE entry=@questid AND language_code='deDE';

set @questid = 8803;
UPDATE quests_localized SET CompletionText	= 'Auf dem Schildchen des Geschenks steht:$b$bFür $N,$B$BIch hoffe, dieses Geschenk wird Euch dabei helfen, einen Hauch von Gemütlichkeit und Festtagsfreude in ganz Azeroth zu verbreiten.$B$BVon Altvater Winter.' WHERE entry=@questid AND language_code='deDE';

set @questid = 8769;
UPDATE quests_localized SET CompletionText	= 'Ein wundervolles Winterhauchfest wünschen Euch Eure Freunde bei Kokelwälder.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7791;
UPDATE quests_localized SET Objectives		= 'Wir suchen derzeit Spender für Wollstoff. Eine grosszügige Spende von 60 Stück Wollstoff würde Eure Anerkennung in Sturmwind wesentlich verbessern. Wir brauchen nur noch 60 Stück von Euch, danach wären wir in der Lage von anderen Leuten genügend Wollstoff für unsere Läden zu erwerben.' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Wunderbar! Lasst Euch für Eure großzügige Spende gedankt sein, $N!' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7807;
UPDATE quests_localized SET Objectives		= 'Wir nehmen zurzeit Spenden für Wolle entgegen. Spendet Ihr 60 Stücke, so wird Euch diese großzügige Tat die volle Anerkennung der Verbannten von Gnomeregan einbringen. Unsere Vorräte würden lediglich 60 Stücke Wollstoff von Euch benötigen; mit der Unterstützung anderer sollten wir unsere Sammelaktion dann erfolgreich vervollständigen können.' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7802;
UPDATE quests_localized SET Objectives		= 'Wir nehmen zurzeit Spenden für Wolle entgegen. Spendet Ihr 60 Stücke, so wird Euch diese großzügige Tat die volle Anerkennung von Eisenschmiede einbringen. Unsere Vorräte würden lediglich 60 Stücke Wollstoff von Euch benötigen; mit der Unterstützung anderer sollten wir unsere Sammelaktion dann erfolgreich vervollständigen können.' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 10352;
UPDATE quests_localized SET Objectives		= 'Wir nehmen zurzeit Spenden für Wolle entgegen. Spendet Ihr 60 Stücke, so wird Euch diese großzügige Tat die volle Anerkennung von Darnassus einbringen. Unsere Vorräte würden lediglich 60 Stücke Wollstoff von Euch benötigen; mit der Unterstützung anderer sollten wir unsere Sammelaktion dann erfolgreich vervollständigen können.' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7792;
UPDATE quests_localized SET Objectives		= 'Wir nehmen zurzeit Spenden für Wolle entgegen. Spendet Ihr 60 Stücke, so wird Euch diese großzügige Tat die volle Anerkennung unseres Volks einbringen.' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Wollstoff bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7793;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzten zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück Seidenstoff habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7808;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzten zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern!' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7803;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzten zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern!' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 10354;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzten zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern!' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7798;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Seide sind, wie fast alle anderen Stoffe auch, so knapp wie nie zuvor. Unterstützen uns noch andere, so bräuchten wir derzeit eine Spende von nicht mehr als 60 Stücken Seide von Euch, um unser Ziel umsetzten zu können.$B$BEine wohlwollende Gabe, sagen wir Seide, könnte Euren hiesigen Ruf in der Gemeinschaft mit Sicherheit verbessern!' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr die 60 Stück Seide bei Euch habt und zu deren Spende bereit seid, dann kann ich sie jetzt entgegennehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7794;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Sturmwind nicht unbeachtet bleiben würde!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück des Magiestoffes habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7804;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Eisenschmiede nicht unbeachtet bleiben würde!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück des Magiestoffes habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7809;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Gnomeregan nicht unbeachtet bleiben würde!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück des Magiestoffes habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 7799;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit in Darnassus nicht unbeachtet bleiben würde!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück des Magiestoffes habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 10356;
UPDATE quests_localized SET Objectives		= 'Unsere Vorräte an Magiestoff gehen zur Neige und wir könnten Eure Hilfe gebrauchen, um unsere Bestände wieder aufzufüllen! Wenn wir uns auf die Gemeinschaft im Ganzen verlassen, bräuchten wir lediglich eine Spende von 60 Stücken Magiestoff von Euch, um unser Ziel umsetzen zu können. Ich versichere Euch, dass eine derartige Großzügigkeit nicht unbeachtet bleiben würde!' WHERE entry=@questid  AND language_code='deDE';
UPDATE quests_localized SET IncompleteText 	= 'Wenn Ihr 60 Stück des Magiestoffes habt und bereit seit, diesen zu spenden, würde ich diese Spende jederzeit gerne annehmen.' WHERE entry=@questid AND language_code='deDE';

UPDATE quests_localized SET IncompleteText='$N - unser Winterhauchfest ist ruiniert, wenn wir unsere Lager nicht mit diesen Leckereien auffüllen können! Graccu kommt bestimmt zu kurz, wenn er dieses Mal seine köstlichen Fleischpasteten mit all den braven Jungs und Mädchen teilen muss...' WHERE entry=6983 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ho, ho, hallo! Ich bin Altvater Winter und ich - mit den besten Wünschen von Kokelwälder... ''Frisch von unserem Hof auf Euren Tisch - beste Kokelwälder Vollwertkost'' - möchte Euch ein phantastisches Winterhauchfest wünschen.$B$BWenn Ihr in diesem Jahr brav wart, dann erhaltet Ihr vielleicht Leckereien von Kokelwälder als Gaumenfreuden zum Winterhauchfest. Hussah!' WHERE entry=7022 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ho, ho, hallo! Ich bin Altvater Winter und ich - mit den besten Wünschen von Kokelwälder... ''Frisch von unserem Hof auf Euren Tisch - beste Kokelwälder Vollwertkost'' - möchte Euch ein phantastisches Winterhauchfest wünschen.$B$BWenn Ihr in diesem Jahr brav wart, dann erhaltet Ihr vielleicht Leckereien von Kokelwälder als Gaumenfreuden zum Winterhauchfest. Hussah!' WHERE entry=7023 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr seid ein wahrer Helfer für den alten Altvater Winter, $N. Ich wünsche Euch ein wunderbares Winterhauchfest.$B$BHier habt Ihr eine Kleinigkeit... Ihr wisst schon, für Eure Mühe.' WHERE entry=7025 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='I-I-Ihr könnt mich h-h-hören! G-G-Gott sei Dank!$B$BIch bin nicht wirklich ein Sch-Sch-Schneemann - mein N-N-Name ist Sacks und ich a-a-arbeite für die N-N-Niederlassung von Kokelwälder in Eisenschmiede. Ich w-w-wurde hierher geschickt, um n-n-nach einem vermissten Paket zu suchen, als ich von einer K-K-Kreatur angegriffen wurde, die ich n-n-noch nie gesehen habe!$B$BSo k-k-kalt...' WHERE entry=7042 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Die Legenden und Überlieferungen um das Winterhauchfest sind über die Jahre in den Gedanken der Völker verblasst. Während ich zugeben muss, dass die Goblins sich bemühen, die Festlichkeiten für ihre eigenen Zwecke wiederzubeleben, mit der Tatsache, dass am Ende dann überall in solcher Art darüber gedacht wird, ist es gut, solche Überlieferungen am Leben zu erhalten.$B$BEuer Wunsch, hinter die Dinge zu sehen und etwas über unsere Vergangenheit zu lernen, ist ein bewundernswerter Wesenszug, $Gjunger:junge; $C. Ich ziehe den Hut vor Eurem gebildeten Charakter!' WHERE entry=7063 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ich heisse Euch im Königreich von Eisenschmiede willkommen, $GFreund:Freundin;. Ich bin immer an denjenigen interessiert, denen es beliebt, sich für das Königreich, sein Volk und seine Geschichten zu interessieren. Seid Ihr deshalb zu mir gekommen?' WHERE entry=7063 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='$N! Habt Ihr ihn gefunden? Enthielten die Notizen in der Mappe, die ich Euch gab, genügend Informationen, um den Aufenthaltsort von Metzel herauszufinden? Ich hasse es, daran zu denken, was diese gemeinen Strolche ihm antun könnten... doch wir können es uns nicht leisten, ein solch halsabschneiderisches Lösegeld zu zahlen!' WHERE entry=8746 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr habt es geschafft! Hurra!$B$BMetzen ist gerade eben erst zurück zu den Ställen von Altvater Winter geflogen. Ja, Metzen kann wirklich fliegen! Der Staub hat ganze Arbeit geleistet, ich wusste, das würde funktionieren. Ihr habt das Winterhauchfest und Kokelwälder vor dem Untergang bewahrt. Danke, $N.$B$BHört mal, weil Ihr das für uns getan habt, möchte ich Euch das hier geben. Das ist etwas GANZ Besonderes. Wenn Ihr ein Reittier habt, werdet Ihr bestimmt eine Menge Spaß damit haben. Frohes Winterhauchfest!' WHERE entry=8762 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='$N! Habt Ihr ihn gefunden? Enthielten die Notizen in der Mappe, die ich Euch gab, genügend Informationen, um den Aufenthaltsort von Metzel herauszufinden? Ich hasse es, daran zu denken, was diese herzlosen Verbrecher ihm antun könnten... doch wir können es uns nicht leisten, ein solch halsabschneiderisches Lösegeld zu zahlen!' WHERE entry=8762 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Aus dem Inneren der Maschine ertönt ein Rumpeln und etwas Dampf entweicht, als sie zu arbeiten beginnt. Kurze Zeit später kündet sich das Ende des Prozesses mit einem weiteren dünnen Dampfstrahl an. Eine Klappe öffnet sich und enthüllt ein Bündel konservierter Tannenzweige!' WHERE entry=8763 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Der „Tannenzweigkonservierer“ sieht auf den ersten Blick wie eine Art Destillierapparat aus, doch eine sorgfältige Untersuchung enthüllt einige goblinische Veränderungen daran. Nach wie vor scheinen Eure Kochkenntnisse Euch aber zu ermöglichen, die Funktionsweise der Maschine zu verstehen.$B$BEs befinden sich bereits frische Tannenzweige darin – Ihr müsst nur noch etwas Tiefsteinsalz und fünf Goldstücke bereitstellten um die Maschine starten zu können.' WHERE entry=8763 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Aus dem Inneren der Maschine ertönt ein Rumpeln und etwas Dampf entweicht, als sie zu arbeiten beginnt. Kurze Zeit später kündet sich das Ende des Prozesses mit einem weiteren dünnen Dampfstrahl an. Eine Klappe öffnet sich und enthüllt ein Bündel konservierter Tannenzweige!' WHERE entry=8799 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Der „Tannenzweigkonservierer“ sieht auf den ersten Blick wie eine Art Destillierapparat aus, doch eine sorgfältige Untersuchung enthüllt einige goblinische Veränderungen daran. Nach wie vor scheinen Eure Kochkenntnisse Euch aber zu ermöglichen, die Funktionsweise der Maschine zu verstehen.$B$BEs befinden sich bereits frische Tannenzweige darin – Ihr müsst nur noch etwas Tiefsteinsalz und fünf Goldstücke bereitstellten um die Maschine starten zu können.' WHERE entry=8799 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Oh, sehr gut! Mit diesen Vorräten sollte ich alle Feiernden auf dem Neujahrsfest bewirten können!$B$BIch danke Euch, $N. Ich stehe in Eurer Schuld. Bitte, nehmt diese Münzen als Dankeschön... und befolgt meinen Rat - nehmt einen herzhaften Schluck aus dem Fass draußen und schließt Euch den anderen beim Feiern des neuen Jahres an!' WHERE entry=8860 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Seid gegrüsst! Seid Ihr wegen der Festlichkeiten hier? Oder wollt Ihr vielleicht einfach nur Eure müden Beine ausruhen?' WHERE entry=8860 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Guten Tag, $C! Seid Ihr wegen der Feierlichkeiten nach Donnerfels gekommen? Oder wollt Ihr nur ein wenig Eure von der Jagd müden Beine ausruhen?' WHERE entry=8861 AND language_code='deDE';

UPDATE quests_localized SET Details='He, könnt Ihr Altvater Winter einen Gefallen tun, ähm $GKleiner:Kleines;?$B$BIch will ja nicht überflüssigerweise über mich selbst in der dritten Person sprechen, aber Altvater Winter arbeitet schon den ganzen Tag hier und könnte selbst eine kleine Leckerei brauchen. Ein paar Lebkuchen und etwas eiskalte Milch, um sie runterzuspülen, wären genau das Richtige. Glaubt Ihr, Ihr könntet dem Altvater eine Freude machen und das für mich besorgen?' WHERE entry=6962 AND language_code='deDE';
UPDATE quests_localized SET Details='He, könnt Ihr Altvater Winter einen Gefallen tun, ähm $GKleiner:Kleines;?$B$BIch will ja nicht überflüssigerweise über mich selbst in der dritten Person sprechen, aber Altvater Winter arbeitet schon den ganzen Tag hier und könnte selbst eine kleine Leckerei brauchen. Ein paar Lebkuchen und etwas eiskalte Milch, um sie runterzuspülen, wären genau das Richtige. Glaubt Ihr, Ihr könntet dem Altvater eine Freude machen und das für mich besorgen?', IncompleteText='All das Plaudern über Gaumenfreuden hat in mir selbst den Wunsch nach etwas Feinem geweckt. Mmmm… Lebkuchen und Milch...' WHERE entry=7025 AND language_code='deDE';

-- 11.01.2013 Thanks to FaceTheSlayer
-- Corrects typos
UPDATE worldstring_tables_localized SET text = 'Ich möchte dieses Gasthaus zu meinem Heimatort machen.' WHERE entry=16 and language_code = 'deDE';
UPDATE worldstring_tables_localized SET text = 'Lehrt mich die Wege der Bestie' WHERE text='Lert mich die Wege der Bestie';

-- 11.01.2013 Danke an Sirala
UPDATE quests_localized SET Details='Ein grosser Berg Geschenke stapelt sich vor dir auf. Ob wohl wirklich irgendwo noch eines für dich dabei ist?$B$B Ja, da...!$B$BAuf einem der Kärtchen glaubst du, deinen Namen zu entdecken...', Objectives='Erfreut ziehst du das sorgfältig verpackte Geschenk aus dem Stapel heraus...' WHERE entry=8744 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein grosser Berg Geschenke stapelt sich vor dir auf. Ob wohl wirklich irgendwo noch eines für dich dabei ist?$B$B Ja, da...!$B$BAuf einem der Kärtchen glaubst du, deinen Namen zu entdecken...', Objectives='Andächtig ziehst du das Festtagsgeschenk aus dem Stapel heraus...' WHERE entry=8803 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein grosser Berg Geschenke stapelt sich vor dir auf. Ob wohl wirklich irgendwo noch eines für dich dabei ist?$B$B Ja, da...!$B$BAuf einem der Kärtchen glaubst du, deinen Namen zu entdecken...', Objectives='Schmunzelnd ziehst du das fröhlich verpackte Geschenk aus dem Stapel heraus...' WHERE entry=8768 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein grosser Berg Geschenke stapelt sich vor dir auf. Ob wohl wirklich irgendwo noch eines für dich dabei ist?$B$B Ja, da...!$B$BAuf einem der Kärtchen glaubst du, deinen Namen zu entdecken...', Objectives='Vorsichtig ziehst du das tickende Geschenk aus dem Stapel heraus...' WHERE entry=8769 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein grosser Berg Geschenke stapelt sich vor dir auf. Ob wohl wirklich irgendwo noch eines für dich dabei ist?$B$B Ja, da...!$B$BAuf einem der Kärtchen glaubst du, deinen Namen zu entdecken...', Objectives='Interessiert ziehst du das leicht geschüttelt wirkende Geschenk aus dem Stapel heraus...' WHERE entry=8788 AND language_code='deDE';

UPDATE quests_localized SET CompletionText='Kil''jaeden knechtet diese Welt mit der ganzen Macht der Brennenden Legion. Sollte die Beschwörung zu Ende geführt werden, wird unsere Welt einmal mehr in die Agonie des Chaos geschleudert. Eurer Mitwirken auf der Insel von Quel''Danas ist für unseren Erfolg gegen die Brennende Legion entscheidend.$B$BUnsere Magier arbeiten daran, die Barrieren niederzureissen, die den Zugang zum Sonnenbrunnen blockieren. Übernehmt Euren Teil im Kampf gegen die Mächte der Legion und helft der Offensive der Zerschmetterten Sonne.' WHERE entry=11550 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='All das Plaudern über Gaumenfreuden hat in mir selbst den Wunsch nach etwas Feinem geweckt. Mmmm… Lebkuchen und Milch...' WHERE entry=6962 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Wenn ich meine vertraute Büchse hätte, wärt Ihr so gut wie tot, $C. Wartet nur, bis die Dampf-Tank-Brigade kommt, um mich zu retten!' WHERE entry=492 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Bleibt mir vom Leibe, widerliche, entsetzliche Kreatur! Möge das Licht mich beschützen! Der Scharlachrote Kreuzzug soll ganz Azeroth von euch befrei…. $B$B… oh, wartet. Ist das etwas zu essen für mich? Ich bin so hungrig…' WHERE entry=407 AND language_code='deDE';
UPDATE quests_localized SET Details='Was auch immer diese Wölfe sich eingefangen haben, es geht nicht weg. Jeden Tag tauchen weitere kranke Wölfe auf. Es tut mir in der Seele weh, dass jemand diese Schöpfungen der Natur in meinem Namen töten muss, aber wir müssen die erkrankten jungen Wölfe erledigen, bevor die lokale Ansteckung zu einer Epidemie wird.$B$BTötet erkrankte junge Wölfe im Tal und bringt mir ihre Pelze als Beweis Eurer Tat.', Objectives='Bringt Eagan Pelzschneider, den Ihr vor der Abtei von Nordhain findet, acht Pelze von erkrankten Wölfen.', CompletionText='Es war eine makabre Aufgabe, aber Ihr hieltet Euren Teil des Geschäfts ein.$B$BIch habe hier ein paar Sachen, die Euch vielleicht gefallen könnten - greift zu!', IncompleteText='Hallo, $N. Wie geht es mit der Jagd auf die erkrankten Wölfe voran?' WHERE entry=33 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Der Baron hat höchstwahrscheinlich mehr Menschen erschlagen, als Ihr in Eurem Leben gesehen habt.' WHERE entry=5263 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ihr könnt tanzen, oder? Versucht es, tippt mit Eurem rechten Fuss zur Mitte… dann nach aussen… wieder zur Mitte… und wackelt einfach überall…' WHERE entry=8360 AND language_code='deDE';
UPDATE quests_localized SET Details='Die Furbolgs der Winterfelle sind dafür bekannt, dass sie zum Schutz vor dunklen Mächten Geisterperlen bei sich tragen. Aber auch diese mächtigen Artefakte vermochten es nicht, die Verderbnis aufzuhalten und so sind die Winterfelle dieser Macht erlegen. Bringt mir die Geisterperlen gefallener Furbolgs der Winterfelle. Für jeweils fünf Geisterperlen die Ihr bei mir abgebt, wird sich Euer Ruf unter den Einwohnern der Holzschlundfeste verbessern.', Objectives='Bringt die Geisterperlen, die Ihr findet, zu Salsa.', IncompleteText='Ihr habt Euch mein Vertrauen hart erarbeitet, $N. Doch bis meine Brüder und Schwestern Euch genauso akzeptieren, wie ich es tue, ist es noch ein weiter Weg. Ihr könnt jedoch etwas für tun, um diesen Prozess zu beschleunigen. Habt Ihr weitere Geisterperlen?' WHERE entry=8469 AND language_code='deDE';
UPDATE quests_localized SET Details='Einige Furbolgs der Totenwaldfelle tragen einen auffälligen Kopfschmuck. Diese wäre ein ausreichender Beweis, für Euren Kampf gegen unsere verderbten Geschwister. Bringt mir die Federn der von Euch erbeuteten Kopfschmucke. Für jeweils fünf Federn die Ihr bei mir abgebt, wird sich Euer Ruf unter den Einwohnern der Holzschlundfeste verbessern.', Objectives='Bringt alle Federn, die ihr findet, zu Grazle.', IncompleteText='Ihr habt Euch mir gegenüber mehr als bewiesen, doch um das Vertrauen meiner misstrauischen Brüder und Schwestern zu gewinnen, ist es noch ein weiter Weg.$BKeine Sorge, ich werde Euch dabei behilflich sein, auch diese letzte Hürde zu überwinden. Habt Ihr mehr Federn?' WHERE entry=8466 AND language_code='deDE';
UPDATE quests_localized SET Details='Wenn Ihr Eure Treue uns gegenüber beweisen wollt, dann gibt es keinen besseren Weg, als diese Oger weiterhin zu bekämpfen.', Objectives='Bringt die Obsidiankriegsperlen zu Aufseher Moi''bff Jill.' WHERE entry=10477 AND language_code='deDE';

UPDATE quests_localized SET Details='Ein Geisselstein des Verderbers ist das Abzeichen eines Lehensherrn der Geissel. Eine mächtige Wesenheit, die Befehlsgewalt über die Geissel  hat, wird immer einen besitzen. Eine solch übelwollende Kreatur zu vernichten, wird sicher die Sache der Argentumdämmerung vorwärtsbringen, so wie alle Bestrebungen des Guten!', Objectives='Bringt Fürst Nicholas Zverenhoff in der Kapelle des Hoffnungsvollen Lichts einen Geisselstein des Verderbers.', CompletionText='Glückwunsch, $N – ich bin erfreut, Euch mit einer Ehrenmarke der Argentumdämmerung auszeichnen zu dürfen! Eine Ehrenmarke solcherart zu erwerben, bezeugt, dass Ihr ein wahrer Held für die Sache des Guten seid.  Wir schätzen alle Anstrengungen, gegen die Geissel vorzugehen, aber einen ihrer Führer zur Strecke zu bringen, bedeutet, ihnen eine wahrhaft vernichtend Niederlage zuzuführen! Für die Dämmerung, $G Bruder:Schwester;!', IncompleteText='Im Auftrag der Argentumdämmerung werde ich Euch eine Ehrenmarke im Austausch für jedes einzelne dieser Abzeichen überreichen. Seid vorsichtig, wenn Ihr Euch eine aneignen wollt, $N – mit solch machtvollen Wesen ist nicht zu spassen!' WHERE entry=5508 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein Geisselstein des Eindringlings ist das Abzeichen der Geissel-Elite-Truppen. Diese sind manchmal in den kampfstärkeren Truppen zu finden, die in den Pestländern stationiert sind. Eine solche Kreatur zu vernichten, ist in der Tat eine Herausforderung, aber eine, die mit dem Auftrag gewürzt sein sollte, das Böse zu bezwingen.', Objectives='Bringt zehn Geisselsteine des Eindringlings zu Fürst Nicholas Zverenhoff in der Kapelle des Hoffnungsvollen Lichts.', CompletionText='Glückwunsch, $N - ich bin erfreut, Euch mit einer Ehrenmarke der Argentumdämmerung auszeichnen zu dürfen!$B$BJede Ehrenmarke, die einem würdigen Empfänger ausgehändigt wird, ist ein Zeichen dafür, dass die Strömung sich gegen die Geissel wendet. Mit mehr und mehr Helden, die in ihrem eigenen Land gegen die Geissel kämpfen, wird die Front der Argentumdämmerung stärker werden, wenn die Zeit kommt, den Krieg gegen das ultimative Böse der Geissel zu wagen. Ich hoffe, dass der Heldenmut, den Ihr gezeigt habt, als es darum ging, diese Zeichen zu erwerben, Euch an diesem Tag ebenfalls mitreissen wird!', IncompleteText='Die Argentumdämmerung offeriert gegenwärtig eine Ehrenmarke im Austausch gegen zehn dieser Abzeichen. Bringt sie mir und ich werde dafür sorgen, dass Ihr Eure Honoration erhaltet.' WHERE entry=5509 AND language_code='deDE';
UPDATE quests_localized SET Details='Ein Geisselstein des Dieners ist das Zeichen der Basis der Geissel. Diese sind manchmal bei den schwächeren Truppen, die in den Pestländern stationiert sind, zu finden, allerdings ist der Begriff „schwächer“  mit Sicherheit im Zusammenhang zu betrachten. Die Geissel, egal, wo sie ist, sollte nie unterschätzt werden.', Objectives='Bringt 20 Geisselsteine des Dieners zu Fürst Nicholas Zverenhoff in der Kapelle des Hoffnungsvollen Lichts.', CompletionText='Glückwunsch, $N - ich bin erfreut, Euch mit einer Ehrenmarke der Argentumdämmerung auszeichnen zu dürfen!$B$B Die Ehrenmarken dienen zwei Zielen. Einerseits können sie genutzt werden, um Euren Rang innerhalb der Argentumdämmerung voranzutreiben; dies wird Euch Möglichkeiten und Belohnungen eröffnen, die unseren geschätzten und verehrten Verbündeten vorbehalten sind. $BAndererseits können sie bei unserem Quartiermeister abgegeben werden, zusammen mit einem Geldbetrag, als Bezahlung für einige der wertvolleren Gegenstände der Dämmerung.$B$BWie immer Ihr Euch entscheidet, wisst, dass Ihr Eure Provision verdient habt. Gut gemacht!', IncompleteText='Die Argentumdämmerung offeriert zurzeit eine Ehrenmarke im Austausch gegen 20 dieser Zeichen – ein Austausch, den ich sehr gerne vornehme, vorausgesetzt, Ihr habt genügend Geisselsteine erworben.' WHERE entry=5510 AND language_code='deDE';

UPDATE npc_text_localized SET text0='Meine Sicht ist mit Visionen von Ereignissen auf der ganzen Welt erfüllt, die geschehen werden oder vielleicht gerade jetzt geschehen.  Viele von ihnen sind düster, doch wir müssen nicht glauben, dass sie nicht abwendbar sind.' WHERE entry=10893 AND language_code='deDe';
UPDATE quests_localized SET IncompleteText='Habt Ihr die Zombie-Herzen, um die ich Euch gebeten habe, $N?' WHERE entry=9216 AND language_code='deDE';
UPDATE quests_localized SET Details='Bereitet man sie richtig auf, kann man aus den Herzen der Untoten mächtige Elixiere gewinnen.$B$BJagt die Zombies in der Todesschneise und bringt mir ihre Herzen.', Objectives='Bringt weiterhin je zehn faulende Herzen zu Magistrix Aminel in Tristessa.', IncompleteText='Habt Ihr weitere Herzen gebracht? Ich kann alle brauchen, die Ihr findet, $N.' WHERE entry=9217 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Habt Ihr die Proben, um die ich Euch ersuchte?' WHERE entry=9218 AND language_code='deDE';
UPDATE quests_localized SET Details='Bringt mir ein paar Einheiten Wirbelknochenstaub und ich werde Euch gerne eine Probe von dem Trank abgeben. Ihr könnt zahlreiche Skelette in der Todesschneise finden, westlich von hier.', Objectives='Bringt jeweils weitere zehn Einheiten Wirbelknochenstaub zu Magistrix Aminel in Tristessa.', CompletionText='', IncompleteText='Habt Ihr mehr Wirbelstaub aufgetrieben? Ich kann so viel brauchen, wie Ihr mir bringt, $N.' WHERE entry=9219 AND language_code='deDE';
UPDATE quests_localized SET Objectives='Sammelt fünf knusprige Spinnenbeine und kehrt zu Meisterkoch Mouldier in Tristessa in den Geisterlanden zurück.', CompletionText='Sehr schön, das dürfte den Zweck erfüllen. Nein, erzählt mir nicht, wie die Dinger rumgekrabbelt sind, ich will es nicht wissen! Ich werde etwas Magie verwenden, dann werden diese Beinchen schon schmackhaft. Ein paar Gewürze, eine Messerspitze Kräuter und natürlich ein paar arkane Zutaten - et voila, ein passendes Mahl für eine Königin...$B$Boder in diesem Fall, eine Dame.$B$BEure Dienste waren zufriedenstellend, $C. Hier, nehmt dieses Rezept und ein paar Portionen.', IncompleteText='Ich glaube, ich kann den leeren Magen der Dame bis hier her knurren hören! Ich gehe davon aus, dass Ihr zu mir kommt, weil Ihr habt, was ich Euch zu beschaffen bat?' WHERE entry=9171 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Habt Ihr den Auftrag erledigt, den ich von Euch verlangt habe, $N?' WHERE entry=0158 AND language_code='deDE';



-- 16-1-2013
set @questid = 1641;
UPDATE quests_localized SET Objectives		= 'Sprecht nochmal mit Duthorian Rall.' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Hier in Sturmwind, bin ich verantwortlich um die Paladine auf dem Weg zu mehr Tugend zu führen, damit sie sich selbst dem Licht widmen und Azeroth vor der Geißel und anderen Bedrohungen verteidigen können.$B$BDie Zeit ist gekommen, Eure ersten Schritte in wahrer Tugenhaftigkeit zu lernen. Wenn Ihr dazu bereit seit, werde ich Euch den Foliant der Offenbarung geben. Beim Studieren dieses Buches werdet Ihr einiges über das Licht lernen und was von Euch erwartet wird. Wenn Ihr dies versteht und befähigt seid, dann werden Ihr erfolgreich in der Lage sein, noch größere Fähigkeiten zu erreichen.' WHERE entry=@questid AND language_code='deDE';

UPDATE quests_localized SET CompletionText='Ich grüsse Euch erneut, $N. Wie kommt Ihr mit den Studien des Folianten der Offenbarung voran?$B$BDann solltet Ihr vorbereitet sein, Euch selbst zu testen. Es gibt immer Aufgaben zu erledigen, in der Stadt und im ganzen Land: Werke des Mitgefühls und des Verständnisses; Menschen, die Hilfe benötigen; Kreaturen zu erschlagen.$B$BWährend auf die Probe gestellt wird, ob Ihr die Geduld aufbringt, anderen zu helfen, speziell denen, die weniger Glück haben, beweist Ihr, dass Ihr ein Diener des Lichts seid und im Vollbesitzt Eurer geistigen Kräfte.' WHERE entry=1642 AND language_code='deDE';

set @questid = 1781;
UPDATE quests_localized SET CompletionText	= '*hust*$B$BEs freut mich Euch zu sehen, $R. Ich bekümmere nicht meine Wunden, der gute Priester hier kann sich zur Zeit um den alten Gazin kümmern. Ich werde die Kraft des Symbols des Lebens, das Ihr da habt, nicht mehr benötigen ... jedenfalls noch nicht.$B$BSo, Duthorian schickt Euch um mit mir zu sprechen, nicht wahr? Fair genug. Ich werde Euch genau erzählen, was mir und meinem Freund Henze geschah. Und mit etwas Glück und etwas Geschick auf Eurer Seite, könnt Ihr vielleicht uns allen noch helfen .' WHERE entry=@questid AND language_code='deDE';


set @questid = 1790;
UPDATE quests_localized SET Objectives		= 'Sprecht nochmal mit Duthorian Rall.' WHERE entry=@questid AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Beeilt Euch, $N. Mehr als nur ein Leben kommt aus dem Gleichgewicht, falls ihr versagt.$B$BWenn Ihr es aus irgendeinem Grund verpasst Henze zu helfen, dann kommt zu mir zurück und ich werde Euch ein anderes Symbol des Lebens für Eure Reisen geben.$B$BMacht nicht den Fehler meine Hilfe als einfache Nächstenliebe zu deuten. Ihr müsst beweisen, dass Ihr wie alle anderen Paladine würdig seid oder das ständige Versagen könnte später auf Euch zurück fallen.' WHERE entry=@questid AND language_code='deDE';

set @questid = 1793;
UPDATE quests_localized SET Objectives		= 'Sprecht nochmal mit Duthorian Rall.' WHERE entry=@questid AND language_code='deDE';

set @questid = 1644;
UPDATE quests_localized SET CompletionText	= 'Danke $N, vielen, vielen Dank!$B$BDie Kinder werden sich freuen und Ihr habt mir so viel Zeit gespart. Jetzt kann ich mich auf die anderen Bedürfnisse der Kinder konzentrieren und mein John hoffentlich früher heimkehren als wir dachten.$B$BNochmals danke, $N. Ich wusste, ich kann mich auf die Barmherzigkeit anderer verlassen. Das Licht sei mit Euch.' WHERE entry=@questid AND language_code='deDE';

-- 17.01.2013 Danke an Sirala
UPDATE quests_localized SET IncompleteText='Endlich! Wir stehen uns von Angesicht zu Angesicht gegenüber, Bruder und $GBruder:Schwester;. Ich heiße Euch in Nordhain willkommen. Hier wird während der kurzen Zeit Euer Zuhause sein, in der Ihr lernt, wie die Dinge laufen, aber wisset, dass Sturmwind nicht weit von hier ist und dass Euer Weg Euch über kurz oder lang dorthin führen wird. Bis dahin, habt Geduld... Ritter der Silberhand.' WHERE entry=3101 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Es ist schön hier in Sturmwind, nicht wahr?$B$BIhr hättet den Zeitpunkt Eures Erscheinens nicht besser wählen können, $N.' WHERE entry=2998 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Schön, Euch Kennen zu lernen, $N. Möge das Licht Euch den rechten Weg weisen und Euch vor dem Bösen beschützen.' WHERE entry=2999 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Willkommen in der Kahtedrale des Lichts, $C.' WHERE entry=3681 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Es ist belegt, dass das Licht mit Euch ist, $N. Aber während die Zeiten immer gefährlicher werden, wird es wichtig, zu wissen, welche Stärke in Euch steckt. Wenn Dämonen, Drachen oder etwas anderes Böses seine Füsse in Euer Land setzt, wird Euer Mut getestet. Werdet Ihr stark genug sein?$B$BTapferkeit, ungeachtet der Situation, ist ebenso ein Teil dessen, was es heisst, Paladin zu sein, wie das Licht, Eure Rüstung und Eure Waffe. Die Schwachen beschützen und den Glauben nicht verlieren, sind zwei weitere Lektionen, die Ihr zu meistern habt, während Ihr in der Kathedrale des Lichts studiert.' WHERE entry=1793 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Es ist belegt, dass das Licht mit Euch ist, $N. Aber während die Zeiten immer gefährlicher werden, wird es wichtig, zu wissen, welche Stärke in Euch steckt. Wenn Dämonen, Drachen oder etwas anderes Böses seine Füsse in Euer Land setzt, wird Euer Mut getestet. Werdet Ihr stark genug sein?$B$BTapferkeit, ungeachtet der Situation, ist ebenso ein Teil dessen, was es heisst, Paladin zu sein, wie das Licht, Eure Rüstung und Eure Waffe. Die Schwachen beschützen und den Glauben nicht verlieren, sind zwei weitere Lektionen, die Ihr zu meistern habt, während Ihr in der Kathedrale des Lichts studiert.' WHERE entry=1794 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ich bin erfreut, Euch zu sehen, $N. Ich weiss, dass Ihr darauf gewartet habt, zu hören, wie Ihr Euer eigenes Streitross erwerben könnt. Und nun ist die Zeit gekommen.$B$BIhr werdet sicherlich in verschiedenen Arten auf die Probe gestellt werden, aber am wichtigsten ist Eure Bereitschaft, all die zahlreichen Hindernisse zu überwinden, die direkt vor Euch liegen. Diese sind nicht als Lernübungen gemacht – Ihr seid über einfache Bildungs-Tests hinaus. Ihr müsst Euren zukünftigen Begleiter vor den Klauen des Bösen sichern, gegen das Ihr Euer ganzes Leben bisher gekämpft habt.$B$BGebt Acht, Eure Zeit ist gekommen!' WHERE entry=7670 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ich bin erfreut, Euch zu sehen, $N. Ich weiss, dass Ihr darauf gewartet habt, zu hören, wie Ihr Euer eigenes Streitross erwerben könnt. Und nun ist die Zeit gekommen.$B$BIhr werdet sicherlich in verschiedenen Arten auf die Probe gestellt werden, aber am wichtigsten ist Eure Bereitschaft, all die zahlreichen Hindernisse zu überwinden, die direkt vor Euch liegen. Diese sind nicht als Lernübungen gemacht – Ihr seid über einfache Bildungs-Tests hinaus. Ihr müsst Euren zukünftigen Begleiter vor den Klauen des Bösen sichern, gegen das Ihr Euer ganzes Leben bisher gekämpft habt.$B$BGebt Acht, Eure Zeit ist gekommen!' WHERE entry=7638 AND language_code='deDE';
UPDATE quests_localized SET Details='Wenn Ihr das Symbol des Lebens verliert, ehe Ihr Henze Faulk erreicht habt, kehrt zu Duthorian Rall in der Kathedrale des Lichts zurück.' WHERE entry=1790 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='So sehen wir uns wieder, $N. Und Ihr seid guter Laune, wie ich sehe.$B$BDas Haus der Stillbrunns ist wieder für einen Tag gerettet, und anhand Eurer Geschichte sehe ich, dass es kein Mangel an Gefahr zu finden gab. Gut gemacht.$B$BDaphne und Jordan haben der Kirche in hohem Masse geholfen, und dass Ihr ihren Besitz beschützt habt – und vor allem ihr Leben – war das Wenigste, das Ihr für sie tun konntet.$B$BFür Euren Mut sollt Ihr belohnt werden.' WHERE entry=1652 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ich hoffe, mein John hat mehr Glück in Eisenschmiede. Er hat so eine Abneigung gegen seine Reisen dorthin, weil er mich und die Kinder alleine lassen muss, aber er weiss, dass es getan werden muss. Er ist so gutherzig.$B$BEinige Jahre sind einfacher, als die anderen, aber dieses ist das Rauste seit langem. Es ist, als ob etwas in der Luft läge, das anzeigt, dass etwas Gewaltiges sich ändert. Wer weiss das schon?' WHERE entry=1644 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr seid so schnell zurück, $N? Und, was habt Ihr in der Zeit vollbracht, die Ihr aus der Kathedrale weg wart?$B$BHabt Ihr einer edlen Sache gedient? Vielleicht habt Ihr etwas über den Wert von Barmherzigkeit gelernt oder etwas mehr über Eure Pflicht gegenüber den Bürgern von Azeroth. Erzählt mir, wem habt Ihr geholfen, und wie…?$B$BOh, ich bin beeindruckt, $N, dies sind sicher die Taten von jemandem, der dem Licht folgt und den Wert anderer über seinen eigenen stellt.$B$BSolche Opfer werden immer zur rechten Zeit belohnt.' WHERE entry=1780 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ist Henze gerettet, $N? Wart Ihr erfolgreich?$B$BZwischen Eurer Handfertigkeit mit der Waffe und der Macht des Lichts, kann ich mir vorstellen, dass Heldenwacht sicher vor allen Bedrohungen durch die Defias ist, aber das wäre dem König und seinen Beratern zu sagen.' WHERE entry=1787 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Habt Dank, $GBruder:Schwester;$B$BDa ich sehe, dass Ihr das Symbol des Lebens handhabt, gehe ich davon aus, dass Duthorian oder Gazin Euch hergeschickt hat?$B$BIch stürzte mich auf die Magier der Defias, als Gazin und ich versuchten, ihre Pläne zu bekommen: Ich konnte sie lange genug aufhalten, um Gazin die Flucht zu ermöglichen, aber am Ende übermannte mich ihre Magie.$B$BAber Ihr habt es geschafft, mich zurück zu bringen: die Fähigkeit, ein Symbol zu benützen, hat nicht einfach jeder, $N. Es verheisst Gutes von Euch, dass Ihr die Fähigkeit hattet, es mit Eurem eigenen Glauben zu ermächtigen.' WHERE entry=1786 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr habt Euch heute wacker geschlagen, $N. Ihr könnt stolz auf das sein, was Ihr erreicht habt.$B$BNoch mehr solche Taten, dann könnt Ihr stolz auf Eure Fähigkeiten sein. Nicht jeder kann die Kraft eines Symbol des Lebens benutzen. Das Licht anrufen, um Tote zurück zu bringen, bedeutet, dass Ihr bereit seid, für eines der grössten Auszeichnungen eines $Cs: die Macht der Auferstehung.$B$BIhr werdet die Macht haben, gefallene Gefährten auferstehen zu lassen, wie Ihr es für Henze getan habt.$B$BSeid gesegnet, $N. Das Licht scheint auf Euch und Ihr solltet es gänzlich Willkommen heissen.' WHERE entry=1788 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Hier in Eisenschmiede bin ich dafür verantwortlich, die Paladine auf den Weg grösserer Rechtschaffenheit zu bringen, indem sie sich ganz dem Licht hingeben und Azeroth vor der Geissel und anderen Bedrohungen verteidigen.$B$BDie Zeit für Euch ist gekommen, Eure ersten Schritte in wahrer Tugendhaftigkeit zu lernen. Wenn Ihr dazu bereit seid, werde ich Euch den Foliant der Offenbarung überreichen. Beim Studieren dieses Buches  werdet Ihr einiges über das Licht erfahren und darüber, was von Euch erwartet wird. Wenn Ihr dies versteht und geeignet seid, dann werdet Ihr Erfolg darin haben, noch grössere Fähigkeiten zu erreichen.' WHERE entry=1645 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Willkommen zurück, $N. Ich hoffe, Ihr habt Eure Zeit damit verbracht, das Buch zu lesen?$B$BDann solltet Ihr vorbereitet sein, Euch selbst zu testen. Es gibt immer Aufgaben zu erledigen, in der Stadt und im ganzen Land: Werke des Mitgefühls und des Verständnisses; Menschen, die Hilfe benötigen; Kreaturen zu erschlagen.$B$BWährend auf die Probe gestellt wird, ob Ihr die Geduld aufbringt, anderen zu helfen, speziell denen, die weniger Glück haben, beweist Ihr, dass Ihr ein Diener des Lichts seid und im Vollbesitzt Eurer geistigen Kräfte.' WHERE entry=1646 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='DAS WAISENHAUS VON STUR... oh, entschuldigt, ich hatte nicht beabsichtigt, Euch anzuschreien, $GSir:Madame;.$B$BMein Name ist John Turner. Wie geht es Euch?$N$NGut, gut, es freut mich, zu hören, dass die Dinge gut für Euch laufen. Ich hatte bereits einen langen Arbeitstag und vermisse meine Frau schrecklich, aber das ist der Preis, den man bezahlen muss, wenn man sich um Nahrung und Kleidung für viele Kinder zu kümmern hat.' WHERE entry=1647 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Durch den Zustrom an Händlern hier und in ganz Azeroth, gibt es ein kleineres Angebot von Dingen, die wir brauchen, um Kleidung für die Kinder unseres Waisenhauses zu machen. Wenn Ihr mir helft, Leinenstoffe zu sammeln, sodass meine Frau neue Kleider für sie machen kann, wäre das sehr edel von Euch, $N. Habt Dank.$b$BHoffentlich kann ich bald nach Hause zu meiner Frau zurückkehren.' WHERE entry=1648 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr seid so schnell zurück, $N? Und, erzählt, welchen Bitten seid Ihr in dieser Zeit nachgekommen?$B$BHabt Ihr einer edlen Sache gedient? Vielleicht habt Ihr etwas über den Wert von Barmherzigkeit gelernt oder etwas mehr über Eure Pflicht gegenüber den Bürgern von Azeroth. Erzählt mir, wem habt Ihr geholfen, und wie…?$B$BBeeindruckend, $N, dies sind sicher die Taten von jemandem, der dem Licht folgt und den Wert anderer über seinen eigenen stellt.$B$BSolche Opfer werden immer zur rechten Zeit belohnt.' WHERE entry=1778 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ich kann Euch nicht genug danken, $GBruder:Schwester;!$B$BIch kann nur vermuten, dass Tiza und Muiredon Euch geschickt haben, um mir zu helfen, wenn Ihr das Symbol des Lebens trägt.$B$Bes ist wahr, ich stürzte mich auf die Dunkeleisen, während ich versuchte, eines ihrer Manuskripte zu ergattern: es war mir möglich, sie lange genug aufzuhalten, um Muiredon die Flucht zu ermöglichen, aber das Licht hat mich vollständig umsponnen, als Ihr vorbei kamt. Die Tatsache, dass Ihr stark genug wart, das Symbol des Lebens zu benutzen, bedeutet Grosses für Euch, aber darüber sprechen wir später.' WHERE entry=1783 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ihr seid zurück! Ich bin froh, Euch zu sehen, $N. Meine Wunden sind verheilt und ich bin bereit, zum Helmsbettsee zurück zu kehren, sobald ich meine Frau davon überzeugen kann, dass es mir gut geht.' WHERE entry=1784 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Ihr habt heute alles getan, um Eisenschmiede eine grosse Gunst zu erweisen, $N. Ich bin stolz, Euch zu uns zählen zu dürfen, und ich fühle, Ihr seid dazu bereit, dass ich Euch mit dieser Papierrolle segne. Das Symbol des Lebens arbeitet nur, wenn es durch $Geinen Paladin:eine Paladina; eingesetzt wird, $Gder:die; bereit für einen der grössten Segen des Lichts bereit ist – die Macht, jemanden vom Tod wieder ins Leben zurück zu bringen.$B$BIch werde Euch in der Fähigkeit unterrichten, Eure gefallenen Gefährten zurück zu holen. Benützt sie weise, $N. Und seid bedankt, in meinem Namen, im Namen meines Mannes und im Namen Eisenschmiedes!' WHERE entry=1785 AND language_code='deDE';

-- 18.2.2013
set @questid = 2998;
UPDATE quests_localized SET Details = 'Seid gegrüßt, $GBruder:Schwester;. Duthorian Rall, einer unserer einflussreichsten Paladine, hat kürzlich von Euch gesprochen. Ich habe mitbekommen, wie er darüber sprach, dass es an der Zeit sei, dass Ihr ein wenig getestet würdet... Dabei fielen auch einige Komplimente darüber, wie gut Ihr bisher abgeschnitten habt.$B$BWenn ich Euch wäre, würde ich nach Sturmwind gehen und mit ihm sprechen, sobald Ihr Zeit habt. Ich bin sicher, er ist in der Kathedrale des Lichts - dort verbringt er einen Großteil seiner Zeit.' WHERE entry=@questid AND language_code='deDE';

-- 22.1.2013
UPDATE items_localized SET name='Langer Bo' WHERE entry=767 AND language_code='deDE';

-- 23.1.2013 Made by Sirala
UPDATE quests_localized SET CompletionText='Schön, Euch kennen zu lernen, $N. Möge das Licht Euch den rechten Weg weisen und Euch vor dem Bösen beschützen.' WHERE entry=2997 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Schön, Euch kennen zu lernen, $N. Möge das Licht Euch den rechten Weg weisen und Euch vor dem Bösen beschützen.' WHERE entry=2999 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Schön, Euch kennen zu lernen, $N. Möge das Licht Euch den rechten Weg weisen und Euch vor dem Bösen beschützen.' WHERE entry=3000 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ihr habt es geschafft! Grossartig!$B$BEs wird noch einiges auf uns zukommen, deshalb bin ich froh, einen mehr im Eisenschmiede-Clan zu haben, auf den ich zählen kann. Für meinen Geschmackt zieht es viel zu viele von uns zur Magie und zum Göttlichen. Nichts gegen sie und ihren Glauben, aber nichts geht über kühlen Stahl in Eurer Hand und einen Schatten, der Euch vor dem Licht verbirgt, wenn Ihr versteht, was ich meine?' WHERE entry=3109 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ha, da seid Ihr ja, $N! Wunderbar!$B$BIch hab'' fast den Glauben verloren, dass Ihr überhaupt hierher kommt… versteht Ihr, den Glauben verloren ? Das ist ein Witz, $N! Ach, macht Euch nichts draus, Ihr seid ja nicht wegen meiner schlechten Witze hergekommen.' WHERE entry=3110 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ah, gut, ein weiteres Memorandum von $Geinem Krieger:einer Kriegerin; auf einer Mission… ist das nicht malerisch?B$BNein, nein, ich möchte Euch nicht foppen, $GKleiner:Kleine;. Ich respektier'' Eure Hartnäckigkeit, soviel ist sicher.  Ich wäre genauso verärgert, wenn Eisenschmiede von den Dunkeleisenzwergen eingenommen würde, also glaubt nicht, ich könnte Eure Notlage nicht nachempfinden…' WHERE entry=3112 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Schön, zu sehen, dass Ihr meine Notiz erhalten habt und hergekommen seid. Entschuldigt, dass es so aussah, als sei es eine Nachricht von einem höheren Tier… keine Beleidigung beabsichtigt. Ich wusste nur, wir beide und andere unseres Schlags müssen zusammenhalten.$B$BEs gibt nicht viele, die es für das Beste der Welt halten, dass Eure und meine Art sich in derselben Stadt verkriechen, aber ich denke, wir können ganz ausgefeilte Dinge ausarbeiten. Was denkt Ihr?' WHERE entry=3113 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Aber nichts von dem ist wichtig. Wichtig ist nur, dass Ihr Euer eigenes Heiliges Licht gesehen habt! Ihr wisst, welche Macht wahrlich von dort kommt. Ihr habt begriffen, dass es viel… klüger ist, eigene Verbündete zu haben. Spezielle Verbündete. Verbündete, die, egal unter welchen Umständen, bis zum letzten Atemzug parieren werden.$B$BUnd das ist der Punkt, an dem ich ins Spiel komme, $N. Ich kann Euch in den Anfängen dieser speziellen Kräfte unterweisen. Sucht mich oft auf und ich werde tun, was ich kann, um Euch mehr Sprüche beizubringen', IncompleteText='Wunderbar! Ihr habt mein Memorandum offensichtlich erhalten.$B$BIgnoriert die Narren um Euch herum, $N. Das Heilige Licht?! Schwert und Schild?! Das sind keine Wege für so aufgeschlossene Wesen, wie wir es sind. Schaut, was die „normale“ Magie unserer Heimat angetan hat. In Zusammenarbeit mit diesen verfluchten Pfuschern wurde unsere Rasse fast ausgelöscht! Und nun müssen wir uns auf die Zwerge verlassen – doch die verbringen lieber Zeit damit, sich mit den Menschen zu verbrüdern, als uns zu helfen, unsere eigene Heimat wieder aufzubauen! Wir sind wie Zweitklass-Bürger! Habt Ihr gesehen, wie sie uns anschauen?!' WHERE entry=3115 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Bedauerlich, dass diese Kreaturen sterben müssen, damit wir zu leben vermögen – wahlloses Töten ist nicht der Weg der Draenei. Wie auch immer, das Blut, das Ihr gesammelt habt, wird unsere Heilkristalle wieder auffrischen, sodass ihr Tod nicht umsonst gewesen ist' WHERE entry=9280 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Bedauerlich, dass diese Kreaturen sterben müssen, damit wir zu leben vermögen – wahlloses Töten ist nicht der Weg der Draenei. Wie auch immer, das Blut, das Ihr gesammelt habt, wird unsere Heilkristalle wieder auffrischen, sodass ihr Tod nicht umsonst gewesen ist.', IncompleteText='$N, habt Ihr schon das benötigte Mottenblut für die Heilkristalle? Überlebende sind über das gesamte Tal verstreut und die Zeit drängt!' WHERE entry=9369 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Jedes Leben ist es Wert, gerettet zu werden, wenn es sich uns nicht widersetzt. Nur unsere Feinde sollten in ewiger Ruhe liegenbleiben.' WHERE entry=9600 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ah, $N – ich glaube, Ihr seid $Geiner der neuen Magier: eine der neuen Magierinnen; hier auf der Insel, nicht wahr? Sehr gut, Ihr seid an den richtigen Ort gekommen. Wenn arkane Meisterschaft das ist, was Ihr sucht, dann kann ich Euch solches Wissen anbieten – so lange Ihr die erforderlichen Mittel habt, die Trainingskosten zu begleichen und die Fähigkeit, Euch auf die Lektionen zu konzentrieren, die ich Euch lehre. Lasst uns starten!' WHERE entry=8328 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ja?' WHERE entry=8563 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ja?' WHERE entry=8564 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ja?' WHERE entry=9393 AND language_code='deDE';
UPDATE quests_localized SET CompletionText='Eure Initiative, mit mir zu sprechen, ermutigt mich.$B$BIn der Vergangenheit war ich für die Ausbildung der jungen Paladine verantwortlich, die sich neu in unseren Orden eingliederten. Dies ist eine Verpflichtung und eine besondere Ehre, die ich demütig erneut auf mich nehme. Euer Name wurde mir gegenüber lobend erwähnt, als jemand, der im Namen des Lichts Gutes zu tun gewillt ist.$B$BEs wäre mir eine Ehre, Euch bei Euren ersten Schritten als Paladin zu unterweisen. Seid Ihr bereit?', IncompleteText='Ich sehe den Stolz in Eurer Brust schwellen. Ihr bildet Euch schon ein, einer der Blutritter zu sein. Ihr werdet Euren Platz unter uns früh genug verdienen.$BAber zuerst müsst Ihr lernen, Euch die Kraft des Lichts nutzbar zu machen und es zu meistern, Eure Waffenfähigkeiten zu verfeinern und Euren Wert zu beweisen. Ihr müsst vorbereitet sein, den Spott auszuhalten, die Angst und den Ekel derjenigen, die Ihr zu verteidigen geschworen habt. $BSo ist es unter denjenigen, die den Preis der grossen Macht nicht begreifen, die sie schützt. Haltet Euren Kopf oben und Eure Klinge bereit, $N.' WHERE entry=9676 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Möge das Licht sich in all Euren Bestrebungen Eurem Willen beugen.' WHERE entry=9678 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Ja?' WHERE entry=9681 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Habt Ihr mit Magister Astalor Blutschwur gesprochen ?' WHERE entry=9684 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Habt Ihr alles erledigt, das ich Euch aufgetragen habe ?' WHERE entry=9692 AND language_code='deDE';
UPDATE quests_localized SET IncompleteText='Gratuliere, $N. Den Rang eines Adepten erreicht zu haben, ist keine durchschnittliche Leistung, glaubt mir. Ich habe viele in dieses Gebäude kommen sehen, und wie wenige von ihnen sind lange genug geblieben, um mich erneut zu besuchen und mir diese Materialien zu bringen.' WHERE entry=9707 AND language_code='deDE';


-- Set LoE German version
REPLACE INTO db_version (db_name, revision) VALUES ('LoE German', 4);

