/**********************************************
 LoE World localization deDE  Rev 7  
 20. May 2013
**********************************************/

REPLACE INTO npc_text_localized (entry, language_code, text0) VALUES (10411, 'deDE', 'Inessera ist ein starke Frau, welche verschiedene Vorlagen zur Herstellung von Schmucksteinen und Bedarfsartikel für das Juwelenschleifen anbietet. Ihr könnt ihr Geschäft im nördlichen Teil der Aldorhöhe finden.');
REPLACE INTO npc_text_localized (entry, language_code, text0) VALUES (10412, 'deDE', 'Lisrythe mag vielleicht zuerst... etwas einschüchternd wirken, aber sie verfügt über alles was Ihr sucht. Sie verkauft ihre Waren ausserhalb der grossen Bibliothek auf der Sehertreppe.');

-- 10.5.2013 Danke an Sirala
UPDATE quests_localized SET CompletionText	= 'Bei meinem Barte! Das beinhaltet eine Macht, die unserer Flugmaschinenflotte Konkurrenz macht! Ich werde es meinen Kriegspriestern geben und wir werden einen Plan ausarbeiten, wie wir diese abscheulichen Nekropolen nach Nordend zurück huschen lassen können… und wir werden direkt hinter ihnen sein!$B$BOh, Muradin, mein Bruder, du musst leben! Bei der Ehre der Bronzebarts, ich werde dich finden!' WHERE entry=12771 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Was ist das? Was für ein Segen! In diesem Artefakt wurde so viel Licht eingefangen, es leuchtet beinahe so hell, wie der Mond! Unsere Priester werden diese Macht gegen unsere Feinde kanalisieren, und die Invasion des Lich-Königs wird mit Garantie fehlschlagen. Habt Dank, $N. Unser Weltenbaum ist gerettet.$B$BDarüberhinaus, wir haben gespürt, dass vielleicht ein weiterer Weltenbaum entspringt, im Norden, sich verborgen an das Herrschaftsgebiet des Lich-Königs anschmiegend. Eines Tages vielleicht… werden wir beide Bäume umsorgen und eine neue Ära des Friedens erschaffen' WHERE entry=12773 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'So, das heilige Volk in Shattrat erschuf, was es versprach! In Hinsicht darauf, dass sie so viele Priester und Paladine ablenken, statt sie gegen die Geissel auszusenden, war dies der richtige Schachzug. Mit dieser heiligen Waffe können wir diesen verfluchten Lich-König und seine Streiter zurück schlagen!$B$BIch werde Euch weiterempfehlen, $G Lord:Lady; $N.' WHERE entry=12774 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ah, ich kann die Macht der Naaru durch dieses Ding scheinen sehen, als ob das Licht selbst darin wohnt! Mit diesem Werkzeug kann Gutes getan werden; die Nekropolen, die aus der gefrorenen Öde im Norden geschickt wurden, werden mit Sicherheit scheitern.' WHERE entry=12776 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Unfassbar makellos! Dieses Instrument bewahrt so viel Licht-Energie, weit über alles hinaus, was bisher bekannt war! Oh, die Anwendungsmöglichkeiten lassen meinen Bart erzittern und rollen mir die Zehennägel auf! Ha ha! Damit könnte ich den Anti-Nächte-Licht-Versprühende Tageslicht-Generierungs-Motor bauen, der die Abenddämmerung zum Morgenrot macht! Die Geissel wird nicht mal ahnen, was sie trifft. Wir werden sie mit einem einzigen Winkelzug alle zerstören! ' WHERE entry=12809 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ein geschäftiger Tag in Ratschet, nicht wahr? Ich liebe es, dem Treiben einer Hafenstadt zuzusehen. So viel Wundersames, so viel Abenteuer...$B$Bso viel Ignoranz.$B$BSehe ich da Hass in Euren Augen, $N? Gut, wir werden daraus einen Vorteil ziehen.' WHERE entry=2996 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Gut, gut, gut! Was haben wir denn hier?$B$BDas ist beeindruckend, $N. Ich hätte es nie für möglich gehalten, aber hier ist er tatsächlich, in meinen Händen, der komplette Foliant der Kabale! $B$BErlaubt mir, ihn einen Augenblick durchzublättern, bevor Ihr wieder geht.' WHERE entry=1803 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Der üble Leutnant Fangor ist also tot? Endlich sind wir diese abscheuliche Kreatur los. Ihr seid sehr tapfer, $C. Die Stadt Seenhain dankt Euch für Eure Hilfe.' WHERE entry=180 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Und nun seid auch Ihr unseren Reihen beigetreten. Versteht mich nicht falsch, $N. Nur, weil Ihr Zugang zur Macht habt, auf die viele neidisch sind, bedeutet dies nicht, dass Ihr einfach akzeptiert werdet. Thrall lässt einen unserer Art nach Orgrimmar, weil wir noch immer seinesgleichen sind - er kann uns nicht den Rücken kehren oder wir würden ebenso pathetisch werden wie die Menschen, die Thrall versklavten. Ich sage nur: seid vorsichtig. Ihr mögt mächtig sein, seid Ihr jedoch tollkühn, seid Ihr so gut wie tot.$B$BWenn Ihr bereit seid für weitere Unterweisungen, sucht mich wieder auf.' WHERE entry=3090 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ja, gut, dass Ihr gekommen seid, $C.' WHERE entry=787 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ach, da ist ja mein Pergament. Ich habe gehört, dass Ihr ins Tal kommen würdet, $N. Freut mich zu sehen, dass Ihr es geschafft habt - hoffen wir nur, dass Ihr die Prüfungen überlebt, die vor Euch liegen. Wie ich bereits sagte: Wenn Eure Macht wächst, kommt zu mir - ich werde tun, was ich kann, um Euch weiter in der Kunst $Geines Kriegers:einer Kriegerin; auszubilden.$B$BViel Glück, $N. Ihr könnt jederzeit wieder zu mir kommen, wenn Ihr Euch bereit fühlt.' WHERE entry=2383 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Willkommen im Tal der Prüfungen, $N. Ihr würdet nicht hier sein, wenn Ihr meine verschlüsselte Schrifttafel nicht hättet entziffern können, darum komme ich gleich zur Sache.$B$BIch bin Rwag und ich bin für das Training der Schurken, Räuber und Taschendiebe zuständig. Ich bin derjenige, zu dem die Zerschmetterte Hand Euch schicket, wenn Ihr noch nicht für das bereit seid, was kommt. Aber keine Sorge, die Hand wird nicht alles überwachen, was Ihr tut. Aber es wird weise sein, mit ihr zusammen zu arbeiten, wenn sie Eure Fähigkeiten braucht.' WHERE entry=3083 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Wieder einer von Kaltunks Rekruten, was?$B$BEs ist wirklich schlecht um die Horde bestellt, wenn das das Beste ist, was wir auf die Beine stellen können. Einerlei. Wenn es so weit ist und wir erkennen, dass Ihr bereit seid, das Tal zu verlassen, werdet Ihr $Gein stolzer:eine stolze; $C der Horde sein.' WHERE entry=4641 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Wunderbar, $N! Wie versprochen, habt Ihr hier Euren Kaktusapfel - und noch ein bisschen was dazu.' WHERE entry=4402 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ja, das ist sehr gut. Diese Informationen zu beschaffen, war gute Arbeit, $N. Hmm...$B$BDie Namen der Offiziere in Tirisfal...$B$BStellt Euch nur vor, welchen Schlag wir der Moral dieser verfluchten Fanatiker verpassen könnten, wenn wir es schaffen, all ihre Anführer auf einen Schlag zu töten.' WHERE entry=383 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Es sieht so aus, als hättet Ihr mich gefunden, $G junger:junge; $C. Melithar ist ein weiser Druide, wenn er Euch geschickt hat' WHERE entry=458 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Nein! Ich war zu spät. Es ist alles meine Schuld.$B$BMeine Untersuchungen hinsichtlich der Aufbereitung alternativer Magiequellen sind mir außer Kontrolle geraten und ich konnte nichts mehr tun, was dies hätte aufhalten können. Wäre ich nur selbst gegangen...$B$Boder hätten sie auf mich gehört und meine Warnungen befolgt!$B$BMeine Hände sind mit Blut befleckt, $C. Ich danke Euch dennoch, dass Ihr diese armen Seelen meiner ehemaligen Lehrlinge erlöst habt. Es ist ein kleiner Trost zu wissen, dass sie nicht länger in dem Zustand verweilen müssen, an dessen Stelle ein Blutelf besser tot wäre.' WHERE entry=8890 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ihr seid in der Tat $Gein aufgeweckter junger Mann:eine aufgeweckte junge Frau;, nicht wahr?$B$BDiese Waren erscheinen mir dem Zwecke angemessen. Für Eure Mühen habt Ihr Euch eine angemessene Entschädigung verdient und vielleicht ein kleines Trinkgeld.$B$BOh, das hätte ich beinahe vergessen! Hier ist eine Einladung zu meinem Fest. Und, $C, wenn Ihr das nächste Mal mein Anwesen betretet, stellt sicher, dass Ihr ein wenig, sagen wir...$B$Bfestlicher gekleidet seid.' WHERE entry=9067 AND language_code='deDE';
UPDATE quests_localized SET CompletionText	= 'Ah, Magistrix Morgenwandler hat zu guter Letzt doch noch auf meine simple Anfrage reagiert. Beizeiten werde ich Ihr Benehmen mit dem Lordregenten erörtern. Sie ist eine recht ungehobelte Person!$B$BNichts, worüber sich $Gein stattlicher Recke:eine Schönheit; wie Ihr $Gunnötige Gedanken machen:das kleine Köpfchen zerbrechen; sollte. Nun, wo Ihr schon mal hier seid, besteht vielleicht die Möglichkeit, dass ich endlich meine Vorräte für das Fest bekomme, auf die ich schon so lange warte.' WHERE entry=9395 AND language_code='deDE';

-- 14.5.2013 Was these customs from arcgdb ?
DELETE FROM gameobject_names_localized WHERE entry BETWEEN 7000001 AND 7000005;

-- Set LoE German version
REPLACE INTO db_version (db_name, revision) VALUES ('LoE German', 7);

